# Generates __init__.pyi stub file from application.yaml for
# IDE autocomplete support.
#
# Usage:
#   python -m src.configs.generate
# ============================================================
import yaml
from pathlib import Path
from typing import Any, Dict


_TYPE_MAP = {
    "str": "str",
    "int": "int",
    "float": "float",
    "bool": "bool",
    "list": "list[str]",
}


def _is_leaf(node: Any) -> bool:
    return isinstance(node, str) and "|" in node


def _is_section(node: Any) -> bool:
    return isinstance(node, dict)


def _parse_pipe(raw: str) -> tuple[str, str, bool]:
    parts = [p.strip() for p in raw.rsplit("|", raw.count("|"))]
    if len(parts) == 3:
        return parts[0], parts[1], parts[2].lower() == "required"
    elif len(parts) == 2:
        return parts[0], parts[1], False
    return raw, "str", False


def _class_name(key: str) -> str:
    return "".join(
        part.capitalize() for part in key.replace("-", "_").split("_")
    )


def _generate_class(
    name: str,
    node: Dict[str, Any],
    indent: int = 0,
) -> list[str]:
    pad = "    " * indent
    lines = [f"{pad}class {_class_name(name)}:"]

    has_attrs = False
    for key, child in node.items():
        python_key = key.replace("-", "_").replace(" ", "_")

        if _is_leaf(child):
            _, type_hint, _ = _parse_pipe(child)
            py_type = _TYPE_MAP.get(type_hint, "Any")
            lines.append(f"{pad}    {python_key}: {py_type}")
            has_attrs = True

        elif _is_section(child):
            nested = _generate_class(python_key, child, indent + 1)
            lines.extend(nested)
            lines.append(f"{pad}    {python_key}: {_class_name(python_key)}")
            has_attrs = True

        else:
            if isinstance(child, bool):
                lines.append(f"{pad}    {python_key}: bool")
            elif isinstance(child, int):
                lines.append(f"{pad}    {python_key}: int")
            elif isinstance(child, float):
                lines.append(f"{pad}    {python_key}: float")
            else:
                lines.append(f"{pad}    {python_key}: str")
            has_attrs = True

    if not has_attrs:
        lines.append(f"{pad}    ...")

    return lines


def generate_stub(
    config_path: str | Path | None = None,
    output_path: str | Path | None = None,
) -> Path:
    configs_dir = Path(__file__).resolve().parent

    if config_path is None:
        config_path = configs_dir / "application.yaml"
    else:
        config_path = Path(config_path)

    if output_path is None:
        output_path = configs_dir / "__init__.pyi"
    else:
        output_path = Path(output_path)

    with open(config_path, "r") as f:
        raw_config = yaml.safe_load(f) or {}

    stub_lines = [
        "# AUTO-GENERATED by src.configs.generate — do not edit manually",
        "# Regenerate: python -m src.configs.generate",
        "",
    ]

    for section_name, section_data in raw_config.items():
        python_name = section_name.replace("-", "_").replace(" ", "_")

        if _is_section(section_data):
            class_lines = _generate_class(python_name, section_data)
            stub_lines.extend(class_lines)
            stub_lines.append("")
            stub_lines.append(f"{python_name}: {_class_name(python_name)}")
        elif _is_leaf(section_data):
            _, type_hint, _ = _parse_pipe(section_data)
            py_type = _TYPE_MAP.get(type_hint, "Any")
            stub_lines.append(f"{python_name}: {py_type}")
        else:
            stub_lines.append(f"{python_name}: Any")

        stub_lines.append("")

    stub_lines.append("def reload_config() -> None: ...")
    stub_lines.append("")

    output_path.write_text("\n".join(stub_lines))
    return output_path


if __name__ == "__main__":
    generate_stub()
    print("Stub generated.")
