"""add extension tables

Revision ID: b2f89f1a59ee
Revises: cbb3dd961d60
Create Date: 2026-04-19 21:50:05.633485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2f89f1a59ee'
down_revision: Union[str, Sequence[str], None] = 'cbb3dd961d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_installs',
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BLACKLISTED', name='install_status_enum'), nullable=False),
    sa.Column('extension_version', sa.String(length=50), nullable=True),
    sa.Column('environment_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blacklisted_by', sa.UUID(), nullable=True),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blacklisted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_installs_email'), 'extension_installs', ['email'], unique=False)
    op.create_index(op.f('ix_extension_installs_google_sub'), 'extension_installs', ['google_sub'], unique=True)
    op.create_table('extension_tokens',
    sa.Column('install_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['install_id'], ['extension_installs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_tokens_install_id'), 'extension_tokens', ['install_id'], unique=False)
    op.create_index(op.f('ix_extension_tokens_token_hash'), 'extension_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extension_tokens_token_hash'), table_name='extension_tokens')
    op.drop_index(op.f('ix_extension_tokens_install_id'), table_name='extension_tokens')
    op.drop_table('extension_tokens')
    op.drop_index(op.f('ix_extension_installs_google_sub'), table_name='extension_installs')
    op.drop_index(op.f('ix_extension_installs_email'), table_name='extension_installs')
    op.drop_table('extension_installs')
    # ### end Alembic commands ###
