"""add inference tables

Revision ID: cbb3dd961d60
Revises: a962d4dd70fa
Create Date: 2026-04-16 14:16:58.573961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbb3dd961d60'
down_revision: Union[str, Sequence[str], None] = 'a962d4dd70fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sender', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.Enum('phishing', 'suspicious', 'legitimate', name='classification_enum'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('link_count', sa.Integer(), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('final_classification', sa.Enum('phishing', 'suspicious', 'legitimate', name='classification_enum'), nullable=True),
    sa.Column('final_confidence', sa.Float(), nullable=True),
    sa.Column('aggregation_note', sa.Text(), nullable=True),
    sa.Column('override_trigger', sa.Enum('page_high_risk', 'page_medium_risk', 'all_low', 'all_failed', 'early_exit', name='override_trigger_enum'), nullable=True),
    sa.Column('pipeline_status', sa.Enum('pending', 'running', 'complete', 'failed', name='pipeline_status_enum'), nullable=False),
    sa.Column('pipeline_stage', sa.Enum('queued', 'classification', 'link_resolution', 'page_analysis', 'aggregation', 'done', name='pipeline_stage_enum'), nullable=False),
    sa.Column('pipeline_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manual_review_flag', sa.Boolean(), nullable=False),
    sa.Column('manual_review_note', sa.Text(), nullable=True),
    sa.Column('manual_review_by', sa.UUID(), nullable=True),
    sa.Column('manual_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manual_override_classification', sa.Enum('phishing', 'suspicious', 'legitimate', name='classification_enum'), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manual_review_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_body_hash'), 'emails', ['body_hash'], unique=False)
    op.create_index(op.f('ix_emails_pipeline_status'), 'emails', ['pipeline_status'], unique=False)
    op.create_index(op.f('ix_emails_received_at'), 'emails', ['received_at'], unique=False)
    op.create_index(op.f('ix_emails_sender'), 'emails', ['sender'], unique=False)
    op.create_index(op.f('ix_emails_submitted_by'), 'emails', ['submitted_by'], unique=False)
    op.create_table('links',
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('is_shortened', sa.Boolean(), nullable=False),
    sa.Column('shortener', sa.String(length=50), nullable=True),
    sa.Column('anchor_context', sa.Text(), nullable=True),
    sa.Column('resolved_url', sa.Text(), nullable=True),
    sa.Column('resolve_status', sa.Enum('success', 'failed', 'timeout', 'blocked', name='resolve_status_enum'), nullable=True),
    sa.Column('redirect_hops', sa.Integer(), nullable=False),
    sa.Column('intermediate_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_email_id'), 'links', ['email_id'], unique=False)
    op.create_table('page_analysis',
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('page_title', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('has_login_form', sa.Boolean(), nullable=False),
    sa.Column('has_payment_form', sa.Boolean(), nullable=False),
    sa.Column('external_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('favicon_matches_domain', sa.Boolean(), nullable=True),
    sa.Column('page_purpose', sa.Text(), nullable=True),
    sa.Column('impersonates_brand', sa.String(length=100), nullable=True),
    sa.Column('requests_credentials', sa.Boolean(), nullable=False),
    sa.Column('requests_payment', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.Enum('high', 'medium', 'low', name='risk_level_enum'), nullable=True),
    sa.Column('risk_confidence', sa.Float(), nullable=True),
    sa.Column('risk_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('scrape_status', sa.Enum('success', 'blocked', 'timeout', 'js_required', name='scrape_status_enum'), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('analysed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_analysis_impersonates_brand'), 'page_analysis', ['impersonates_brand'], unique=False)
    op.create_index(op.f('ix_page_analysis_link_id'), 'page_analysis', ['link_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_analysis_link_id'), table_name='page_analysis')
    op.drop_index(op.f('ix_page_analysis_impersonates_brand'), table_name='page_analysis')
    op.drop_table('page_analysis')
    op.drop_index(op.f('ix_links_email_id'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_emails_submitted_by'), table_name='emails')
    op.drop_index(op.f('ix_emails_sender'), table_name='emails')
    op.drop_index(op.f('ix_emails_received_at'), table_name='emails')
    op.drop_index(op.f('ix_emails_pipeline_status'), table_name='emails')
    op.drop_index(op.f('ix_emails_body_hash'), table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
