"""add extension analyse events

Revision ID: d872777cf62a
Revises: b2f89f1a59ee
Create Date: 2026-04-19 22:01:08.539937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd872777cf62a'
down_revision: Union[str, Sequence[str], None] = 'b2f89f1a59ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_analyse_events',
    sa.Column('install_id', sa.UUID(), nullable=False),
    sa.Column('predicted_label', sa.String(length=16), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['install_id'], ['extension_installs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extension_analyse_events_install_id'), 'extension_analyse_events', ['install_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extension_analyse_events_install_id'), table_name='extension_analyse_events')
    op.drop_table('extension_analyse_events')
    # ### end Alembic commands ###
